uploads = []
generated = []

[[outputs]]
id = "P1MfCG8NOdNJPPGp81YSN"
uri = "file://brainepedia-deploy.zip"
type = "unspecified"
title = "brainepedia-deploy.zip — IIS Node deployment build"

[[outputs]]
id = "gC1gJju_G_fkS_YWvNAgi"
uri = "file://brainepedia-dist.zip"
type = "unspecified"
title = "Brainepedia — Production Build (dist.zip)"
