import {
  LayoutDashboard,
  Building2,
  Users,
  Lock,
  UserCheck,
  BarChart3,
  CreditCard,
  Gem,
  Settings,
  Search,
  Bookmark,
  BriefcaseBusiness,
  ClipboardList,
  FilePlus2,
  GraduationCap,
  IdCard,
} from "lucide-react";
import type { NavItem } from "@/components/dashboard/DashboardShell";

export const EMPLOYER_NAV: NavItem[] = [
  { href: "/employer/overview", label: "Dashboard", icon: LayoutDashboard },
  { href: "/employer/candidates", label: "Candidate Explorer", icon: Search, section: "Recruitment" },
  { href: "/employer/saved-candidates", label: "Saved Candidates", icon: Bookmark },
  { href: "/employer/candidate-dossiers", label: "Candidate Dossiers", icon: IdCard },
  { href: "/employer/jobs/create", label: "Create Job", icon: FilePlus2, section: "Jobs" },
  { href: "/employer/jobs", label: "My Job Postings", icon: BriefcaseBusiness },
  { href: "/employer/applications", label: "Applications", icon: ClipboardList },
  { href: "/employer/challenges", label: "Private Challenges", icon: Lock, section: "Assessments" },
  { href: "/employer/assessments", label: "Candidate Assessments", icon: UserCheck },
  { href: "/employer/team", label: "Team Members", icon: Users, section: "Teams" },
  { href: "/employer/analytics", label: "Team Analytics", icon: BarChart3 },
  { href: "/employer/challenges", label: "Training Challenges", icon: GraduationCap },
  { href: "/employer/company-profile", label: "Company Profile", icon: Building2, section: "Organization" },
  { href: "/employer/subscription", label: "Subscription", icon: Gem },
  { href: "/employer/billing", label: "Billing", icon: CreditCard },
  { href: "/employer/settings", label: "Settings", icon: Settings, section: "Account" },
];
