import {
  Activity,
  Award,
  BriefcaseBusiness,
  ClipboardCheck,
  CreditCard,
  FileText,
  LayoutDashboard,
  Map,
  MessageSquare,
  Settings,
  Sparkles,
  Star,
  Trophy,
  User as UserIcon,
  Zap,
} from "lucide-react";
import type { NavItem } from "@/components/dashboard/DashboardShell";

export const USER_NAV: NavItem[] = [
  { href: "/user/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/profession/select", label: "Districts", icon: Map, section: "My Journey" },
  { href: "/user/missions", label: "Missions", icon: Sparkles },
  { href: "/user/experience-sessions", label: "Experience Sessions", icon: Activity },
  { href: "/user/xp-progress", label: "XP Progress", icon: Zap, section: "Growth" },
  { href: "/user/vx-progress", label: "VX Progress", icon: Award },
  { href: "/user/badges", label: "Badges", icon: Trophy },
  { href: "/user/achievements", label: "Achievements", icon: Star },
  { href: "/forum", label: "Forum", icon: MessageSquare, section: "Community" },
  { href: "/forum/discussions", label: "Discussions", icon: FileText },
  { href: "/forum/my-discussions", label: "My Discussions", icon: UserIcon },
  { href: "/jobs", label: "Job Feed", icon: BriefcaseBusiness, section: "Career" },
  { href: "/user/applications", label: "Applications", icon: FileText },
  { href: "/user/assessments", label: "Assessments", icon: ClipboardCheck },
  { href: "/user/portfolio", label: "Public Portfolio", icon: UserIcon, section: "Profile" },
  { href: "/user/subscription", label: "Subscription", icon: CreditCard },
  { href: "/user/settings", label: "Settings", icon: Settings },
];
